src/Entity/ServiceGarage.php
<?php

namespace App\Entity;

use App\Repository\ServiceGarageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ServiceGarageRepository::class)]
#[Vich\Uploadable]
class ServiceGarage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;



        // ... other fields

    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'voiture_images', fileNameProperty: 'image' )]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $image = null;

    

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;


    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $services = null;

 

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $servicereparation = null;

    #[ORM\Column(nullable: true)]
    private ?int $tarifs = null;

    #[ORM\Column(nullable: true)]
    private ?int $telephone = null;

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getDescription(): ?string
    {
        return $this->Description;
    }


    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImage(?string $image): void
    {
        $this->image = $image;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }
   

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getServices(): ?string
    {
        return $this->services;
    }

  


    public function getServicereparation(): ?string
    {
        return $this->servicereparation;
    }

    public function setServicereparation(?string $servicereparation): static
    {
        $this->servicereparation = $servicereparation;

        return $this;
    }

    public function getTarifs(): ?int
    {
        return $this->tarifs;
    }

    public function setTarifs(?int $tarifs): static
    {
        $this->tarifs = $tarifs;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(?int $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }
}

src/Controller/CrudController.php
<?php

namespace App\Controller;


use App\Form\CarType;
use App\Entity\Product;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Repository\HorairesOuvertureRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CrudController extends AbstractController
{
    /**
     * Undocumented function
     *
     * @param ProductRepository $repository
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    #[Route('/crud', name: 'app_crud' , methods:['GET'])]
    public function index(ProductRepository $repository, PaginatorInterface $paginator, Request $request): Response
    {
        $products = $paginator->paginate(
            $repository->findAll(),
            $request->query->getInt('page', 1), 
            10 
        );
        return $this->render('pages/crud/index.html.twig', [
           'products'=>$products
        ]);
    }

    // Création d'un nouveau Produit
    
    #[Route('/nouveau/car', name:'nouveau_car',methods:['GET','POST'])]
    public function new(Request $request, EntityManagerInterface $manager):Response
    {
        
        $product= new Product();
        $form = $this->createForm(CarType::class, $product);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
           $product =$form->getData();

           $manager->persist($product);
           
           $manager->flush();
           $this->addFlash(
            'success',
            'votre voiture a été bien rajouté dans le système',

           );
           return $this->redirectToRoute('app_crud');
         
        }
      
        return $this->render('pages/crud/nouveau_car.html.twig',[
            'form'=>$form->createView(),
           
        ]);
    }

    // Modifier mes produits 
    /**
     * @param Product $product
     * 
     */
    #[Route('/modifier/car/{id}', 'app_modifier', methods:['GET','POST'])]
    public function edit( ProductRepository $repository,int $id ,Request $request, EntityManagerInterface $manager): Response
    {
        $product= $repository->findOneBy(['id'=>$id]);
        $form = $this->createForm(CarType::class, $product);
        
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
           $product =$form->getData();
          
           $manager->persist($product);
           
           $manager->flush();
           $this->addFlash(
            'success',
            'votre voiture a été bien modifié dans le système',

           );
           return $this->redirectToRoute('app_crud');
         
        }
        return $this->render('pages/crud/modifier_car.html.twig',[
           'form'=> $form->createView(),
        ]);

       }

       // function delete
       #[Route('/supprimer/car/{id}','app_supprimer', methods:['GET','POST'])]
       public function delete(ProductRepository $repository,int $id , EntityManagerInterface $manager):Response
       {
        $product= $repository->findOneBy(['id'=>$id]);
        $manager->remove($product);
        $manager->flush();
        $this->addFlash(
            'success',
            'votre voiture a été bien supprimé dans le système',

           );
           return $this->redirectToRoute('app_crud');
         
          
        
       
    }
}
    
    

templates/pages/crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des voitures{% endblock %}

{% block body %}
          {% for message in app.flashes('success') %}
    <div class="alert alert-success w-75 text-center text-warning-emphasis">
        {{ message }}
    </div>
{% endfor %}
      <div class=" container-table-product">
        <div class="row">
         <div class="col-9">
          <h1>Liste des voitures</h1>
  
         

                      <div class="count col-md-3 w-100 bg-dark text-light mx-2 ">
      ℑ𝔩 𝔶'𝔞 {{ products.getTotalItemCount }} 𝔳𝔬𝔦𝔱𝔲𝔯𝔢𝔰
      <span> <a class="btn btn-light btn-sm ms-5 text-danger text-bold" href="{{path('nouveau_car')}}"> Créer une nouvelle voiture</a></span>
</div>

          <table class=" mx-2 bg-light  text-center ">
  <thead class="thead-crud">
    <tr>
      <th>#Id</th>
      <th>Model</th>
      <th>Image</th>
      <th>Prix</th>
      <th>Promo</th>
      <th>k/m</th>
      <th>Année</th>
      <th>Caractéristique</th>
      <th>Content</th>
       <th>Numéro-Téléphone</th>
      <th>Option</th>

    </tr>
  </thead>
      {% for product in products %}
  <tbody >
    <tr>
     <td class="bg-dark text-light">{{product.id}}</td>
     <td>{{product.name}}</td>
     <td><img style="max-width:150px;" src="{{vich_uploader_asset(product,'imageFile')}}" alt="" class =""<card-img-top> </td>
     <td>{{product.price}} </td>
     <td> {% if product.promo %}
        <div class="text text-danger ">Promo </div>
        {% endif %} </td>
     <td>{{product.kilometrage}} </td>
     <td>{{product.years}}</td>  
     <td>{{product.description}}</td> 
     <td>{{product.content}}</td>  
      <td>{{product.numeroTelephone}}</td>  
     <td >
     <div class="d-flex">
      
     <a class="btn btn-light btn-sm ms-5 text-light bg-success " href="{{path('app_modifier', {id: product.id})}}"> Modifier</a>
     <a class="btn btn-light btn-sm ms-5 text-light bg-danger" href="{{path('app_supprimer',{id: product.id})}}"> Supprimer</a>

</div>
     </td>  
      
      
     </tr> 
  </tbody>
   {% endfor %}
</table>
    
        </div> 
   
        
        </div> 
 
      </div>
           {# display navigation #}
<div class="navigation d-flex justify-content-center mt-3">
    {{ knp_pagination_render(products) }}
</div>
{% endblock %}

templates/pages/crud/modifier_car.html.twig
{% extends 'base.html.twig'%}

{% block body %}

<div class="container bg-dark">
   <div class="row">
      <h1 class="text-light" > Modifier les voitures</h1>
     <hr class="text-light"> 
      {{form_start(form)}}
      
      <div class=" d-flex">
      <div class="m-4 text-light">
      {{form_row(form.name)}}
      </div>
       <div class="m-4 text-light">
       {{form_row(form.price)}}
        </div>
         <div class="m-4 text-light">
      {{form_row(form.kilometrage)}}
      </div>
        <div class="m-4 text-light">
       {{form_row(form.years)}}
        </div>

      </div>

          <div class="m-3 w-50 text-light mb-2">
       {{form_row(form.category)}}
        </div>
      <!---->

         
         <div class="m-3 w-50 text-light">
       {{form_row(form.description)}}
        </div>

          <div class="m-3 w-50 text-light">
       {{form_row(form.content)}}   
        </div>

        
                  <div class="m-3 w-50 text-dark">
       {{form_row(form.numero_telephone)}}   
        </div>     
      


         <div class="m-3 w-50 text-light">
       {{form_row(form.promo)}}
        </div>
       
    
   
     <div class="m-3  text-light  ">
        {{form_row(form.imageFile)}}
      </div>
 
   
      </div>





      {{form_end(form)}}
   </div>
</div>

{% endblock  %}

templates/pages/crud/nouveau_car.html.twig
{% extends 'base.html.twig'%}

{% block body %}

<div class="container ">
   <div class="row">
      <h1 class="text-dark" > Création d'un nouveau voiture</h1>
     <hr class="text-dark"> 
      {{form_start(form)}}
      
      <div class=" d-flex">
      <div class="m-4 text-dark">
      {{form_row(form.name)}}
      </div>
       <div class="m-4 text-dark">
       {{form_row(form.price)}}
        </div>
         <div class="m-4 text-dark">
      {{form_row(form.kilometrage)}}
      </div>
        <div class="m-4 text-dark">
       {{form_row(form.years)}}
        </div>

       
      </div>
      <div class=" d-flex">
         <div class="m-4 text-dark">
       {{form_row(form.nombre_de_place)}}
        </div>
         <div class="m-4 text-dark">
        {{form_row(form.huile)}}
         </div>
          <div class="m-4 text-dark">
         {{form_row(form.boite_de_vitesses)}}
        </div>
 </div>

          <div class="m-3 w-50 text-dark mb-2">
       {{form_row(form.category)}}
        </div>
      <!---->

         
         <div class="m-3 w-50 text-dark">
       {{form_row(form.description)}}
        </div>

          <div class="m-3 w-50 text-dark">
       {{form_row(form.content)}}   
        </div>

        
     
               <div class="m-3 w-50 text-dark">
       {{form_row(form.numero_telephone)}}   
        </div>


         <div class="m-3 w-50 text-dark">
       {{form_row(form.promo)}}
        </div>
       
    
   
     <div class="m-3  text-dark ">
        {{form_row(form.imageFile)}}
      </div>

       
   
      </div>





      {{form_end(form)}}
   </div>
</div>

{% endblock  %}