src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $create_at = null;

    #[ORM\OneToMany(mappedBy: 'commentaire', targetEntity: Product::class)]
    private Collection $commenter;

    public function __construct()
    {
        $this->commenter = new ArrayCollection();
     $this->create_at = new \DateTimeImmutable;
    } 


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(?\DateTimeImmutable $create_at): static
    {
        $this->create_at = $create_at;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getCommenter(): Collection
    {
        return $this->commenter;
    }

    public function addCommenter(Product $commenter): static
    {
        if (!$this->commenter->contains($commenter)) {
            $this->commenter->add($commenter);
            $commenter->setCommentaire($this);
        }

        return $this;
    }

    public function removeCommenter(Product $commenter): static
    {
        if ($this->commenter->removeElement($commenter)) {
            // set the owning side to null (unless already changed)
            if ($commenter->getCommentaire() === $this) {
                $commenter->setCommentaire(null);
            }
        }

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;



use App\Entity\Categories;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProductRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Cascade;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[Vich\Uploadable]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: "Nom voiture doit comporter au moins {{ limit }} caractères",
        maxMessage: "Nom voiture doit comporter au moins {{ limit }} caractères",
    )]
    private ?string $name = null;

        // ... other fields

    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'voiture_images', fileNameProperty: 'image' )]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $image = null;

    

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;


    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    private ?int $kilometrage = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    private ?int $years = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    

    #[ORM\Column]
    private ?bool $promo = null;

    #[ORM\ManyToMany(targetEntity: Categories::class, inversedBy: 'products')]
    private Collection $category;

    #[ORM\ManyToMany(targetEntity: ContactAnnonce::class, mappedBy: 'nameAnnonce')]
    private Collection $contactAnnonces;


    private ?float $moyenne = null;

    #[ORM\ManyToOne(inversedBy: 'commenter')]
    private ?Commentaire $commentaire = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $huile = null;

    

    #[ORM\Column(nullable: true)]
    private ?int $nombreDePlace = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $boiteDeVitesses = null;

    #[ORM\Column(nullable: true)]
    private ?int $numeroTelephone = null;

  

    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->contactAnnonces = new ArrayCollection();
      
      
        
      
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    
    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImage(?string $image): void
    {
        $this->image = $image;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }
   





    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getKilometrage(): ?int
    {
        return $this->kilometrage;
    }

    public function setKilometrage(int $kilometrage): static
    {
        $this->kilometrage = $kilometrage;

        return $this;
    }

    public function getYears(): ?int
    {
        return $this->years;
    }

    public function setYears(int $years): static
    {
        $this->years = $years;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

   

    public function isPromo(): ?bool
    {
        return $this->promo;
    }

    public function setPromo(bool $promo): static
    {
        $this->promo = $promo;

        return $this;
    }

    /**
     * @return Collection<int, Categories>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Categories $category): static
    {
        if (!$this->category->contains($category)) {
            $this->category->add($category);
        }

        return $this;
    }

    public function removeCategory(Categories $category): static
    {
        $this->category->removeElement($category);

        return $this;
    }

    /**
     * @return Collection<int, ContactAnnonce>
     */
    public function getContactAnnonces(): Collection
    {
        return $this->contactAnnonces;
    }

    public function addContactAnnonce(ContactAnnonce $contactAnnonce): static
    {
        if (!$this->contactAnnonces->contains($contactAnnonce)) {
            $this->contactAnnonces->add($contactAnnonce);
           
        }

        return $this;
    }

    public function removeContactAnnonce(ContactAnnonce $contactAnnonce): static
    {
        if ($this->contactAnnonces->removeElement($contactAnnonce)) {
           
        }

        return $this;
    }

 
    public function __toString()
    {
        return $this->name;
     
    }

    public function getMoyenne()
    {
       $notes= $this->notes;
 
       if($notes->toArray()== []){
          $this->moyenne = null;
          return $this->moyenne;
       }
       $total =0;
        foreach($notes as $note){
          $total+=$note->getNote();
        }
        $this->moyenne = $total / count($notes);
        return $this->moyenne;
    }

    public function getCommentaire(): ?Commentaire
    {
        return $this->commentaire;
    }

    public function setCommentaire(?Commentaire $commentaire): static
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getHuile(): ?string
    {
        return $this->huile;
    }

    public function setHuile(?string $huile): static
    {
        $this->huile = $huile;

        return $this;
    }

   

    public function getNombreDePlace(): ?int
    {
        return $this->nombreDePlace;
    }

    public function setNombreDePlace(?int $nombreDePlace): static
    {
        $this->nombreDePlace = $nombreDePlace;

        return $this;
    }

    public function getBoiteDeVitesses(): ?string
    {
        return $this->boiteDeVitesses;
    }

    public function setBoiteDeVitesses(?string $boiteDeVitesses): static
    {
        $this->boiteDeVitesses = $boiteDeVitesses;

        return $this;
    }

    public function getNumeroTelephone(): ?int
    {
        return $this->numeroTelephone;
    }

    public function setNumeroTelephone(?int $numeroTelephone): static
    {
        $this->numeroTelephone = $numeroTelephone;

        return $this;
    }

   

   
 
}

src/Entity/ServiceGarage.php
<?php

namespace App\Entity;

use App\Repository\ServiceGarageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ServiceGarageRepository::class)]
#[Vich\Uploadable]
class ServiceGarage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;



        // ... other fields

    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'voiture_images', fileNameProperty: 'image' )]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $image = null;

    

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;


    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $services = null;

 

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $servicereparation = null;

    #[ORM\Column(nullable: true)]
    private ?int $tarifs = null;

    #[ORM\Column(nullable: true)]
    private ?int $telephone = null;

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getDescription(): ?string
    {
        return $this->Description;
    }


    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImage(?string $image): void
    {
        $this->image = $image;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }
   

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getServices(): ?string
    {
        return $this->services;
    }

  


    public function getServicereparation(): ?string
    {
        return $this->servicereparation;
    }

    public function setServicereparation(?string $servicereparation): static
    {
        $this->servicereparation = $servicereparation;

        return $this;
    }

    public function getTarifs(): ?int
    {
        return $this->tarifs;
    }

    public function setTarifs(?int $tarifs): static
    {
        $this->tarifs = $tarifs;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(?int $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;


use App\Entity\Note;
use App\Form\NoteType;
use App\Data\SearchData;
use App\Form\SearchForm;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\NoteRepository;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\CommentaireRepository;
use App\Repository\HorairesOuvertureRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProductController extends AbstractController
{
    /**
     * Undocumented function
     *
     * @param ProductRepository $repository
     * @param Request $request
     * @return Response
     */
    #[Route('/voiture/occasion', name: 'app_product', methods:['GET','POST'])]
    public function index(ProductRepository $repository ,Request $request,
    EntityManagerInterface $manager, CommentaireRepository $commentairerepository, NoteRepository $noterepository, HorairesOuvertureRepository $horairerepository): Response
    {
         //horaires
        // notes 
      
        $notes= new Note();
        $formnote= $this->createForm(NoteType::class, $notes);
        $formnote->handleRequest($request);
       
        if($formnote->isSubmitted() && $formnote->isValid()){
           $notes=$formnote->getData();

           $manager->persist($notes);
           
           $manager->flush();
          
           return $this->redirectToRoute('app_product');
         
        }

       //  filter voiture 
        $data = new SearchData();
        $data->page = $request->get('page',1);
        $form = $this->createForm(SearchForm::class, $data);
        $form->handleRequest($request);
        $products = $repository->findSearch($data);
        

         $commentaire= new Commentaire();
         $formcommentaire = $this->createForm(CommentaireType::class, $commentaire);
         $formcommentaire->handleRequest($request);
         
         if($formcommentaire->isSubmitted() && $formcommentaire->isValid()){
          
            $commentaire =$formcommentaire->getData();
           
            $manager->persist($commentaire);
          
            $manager->flush();

            return $this->redirectToRoute('app_product');
          
         }
         $horaire=$horairerepository->findAll();
         $notes=$noterepository->findAll();
         $commentaire= $commentairerepository->findAll();
         return $this->render('product/index.html.twig',[ 
            'products'=>$products,
            'form'=>$form->createView(),
            'formcommentaire'=> $formcommentaire->createView(),
            'commentaire'=> $commentaire,
            'formnote'=>$formnote->createView(),
            'notes'=>$notes,
            'horaire'=> $horaire
           
        ]);
    
    }
    
    #[Route('/supprime/commentaire/{id}','supprimer_commentaire', methods:['GET','POST'])]
    public function deleteEmail(CommentaireRepository $commentairerepository,int $id , EntityManagerInterface $manager):Response
    {
     $commentaire= $commentairerepository->findOneBy(['id'=>$id]);
     $manager->remove($commentaire);
     $manager->flush();
   
        return $this->redirectToRoute('app_product');
   
    }
}
    

templates/product/_cart.html.twig
   
 
    <div class="card  mt-5">
      
<img src="{{vich_uploader_asset(product,'imageFile')}}" alt="" class =""<card-img-top>
<div class="card-body ">
   <h5 class="card-title">{{product.name}}</h5>
   <div class="card-title  text text-primary" style="font-weight:bold; font-size:1.5rem"> {{product.price | number_format(0,',',' ')}} €
        {% if product.promo %}
         <div class="text text-warning ">Promo $</div>
        {% endif %}
   </div>
     <div class="card-title "> {{product.kilometrage}} k/m</div>
     <div class="card-title ">Année {{product.years}} </div>
     
      <p class="text text-muted "> {{product.description}}</p>
      <p class="text text-muted "> {{product.content}}</p>

       <a style="color:red;" href="tel:+33749553121"> <span class="text-dark">Tel:</span>{{product.numeroTelephone}}</a> 

      <div>
         {% for c in product.category %}
       <em class="text-muted  text-primary text-italic">#{{c.name}}</em> 
         {% endfor %}
       
      </div>

         <div>
         
    
 </div>
  
</div>
 <a class="link-annonce" style="background: rgb(19, 116, 4); width:90px;text-decoration:none; color:white;box-shadow: 0px 5px 9px black;
 
 " href="{{path('app_ContactAnnonce',{'id': product.id})}}">Annonce</a>
 
   </div>


</body>
</html>
 

templates/product/_filter.html.twig
{{form_start(form, {attr: {class: 'filter'}})}}
    <h5 class ="text-light text center mt-3" > Recherche</h5>
     <div class=" w-100 mt-5">
    {{form_widget(form.q)}}
    </div>
    <hr>

  <h5 class ="text-light text center mt-3" > Filter</h5>
<h6 class=" mt-5" style="font-size:17px; font-weight: 700; color: rgb(69, 2, 2);">Modele des Voitures</h6>
   {{form_row(form.Category)}}
     <hr>
 <h6 class="text-danger ">Prix</h6>
<div class="row">
   <div class="col-md-6 ">
      {{form_row(form.pmin)}}
   </div>

    <div class="col-md-6">
        {{form_row(form.pmax)}}
    </div>
</div>
<!-- slider prix-->
<div id="price-slider"></div>
  
<h6 class="text-danger mt-2">Kilométrage</h6>

<div class="row">
    <div class="col-md-6">
       {{form_row(form.kmin)}}
     </div>

    <div class="col-md-6 ">
       {{form_row(form.kmax)}}
    </div>
</div>

<h6 class="text-danger mt-2">Années</h6>

<div class="row">
    <div class="col-md-6">
        {{form_row(form.amin)}}
    </div>

    <div class="col-md-6">
       {{form_row(form.amax)}}
     </div>
</div>
  <hr>
<div class="  w-50  text-dark rounded-4 bg-light text-center">{{form_row(form.promo)}}</div>
<hr>

<button type ="submit" class="btn btn-warning w-100 text-center mt-3 mb-3">filtrer</button>
{{form_end(form)}}

templates/product/_notes.html.twig
 

 {% block body %}
  <div class="note">
{{form_start(formnote)}}
     
                  <h5 class="text-dark ms-5"> avis de client</h5>
              
               <div class="d-flex">
               
                  {{form_row(formnote.submit)}}
                   {{form_row(formnote.note)}} 
                   {{form_row(formnote.Prenom)}}
                   
                  {% for note in notes %}
                 <div class="text-light py-4 px-5 ms-3 w-100">  Votre note est de <span class="text-warning">{{note.note}}</span>/5</div>
                 <br>
              {% endfor %}
              
         </div>
             
    
              

{{form_end(formnote)}}
 </div>
{% endblock %}

templates/product/commentaire.html.twig
   <div class="container w-100" >
   <section >
  
  <div class="container my-5 py-2 w-100">
    <div class="row d-flex justify-content-center">
     <div class="d-flex justify-content-center ">
          <div class=" px-auto w-100 ">
             {% include  'product/_notes.html.twig' %}
          </div>
         </div>
      <div class="col-md-10 col-lg-10 col-xl-8">
        <div class="card">
          <div class="card-body">
          
            <div class="d-flex flex-start align-items-center">
              <img class="rounded-circle shadow-1-strong me-3"
                src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(19).webp" alt="avatar" width="60"
                height="60" />
              <div >
                <h6 class="fw-bold text-primary mb-1">Client</h6>
                <p class="text-muted small mb-0">
                  Shared publicly - Jan 2020
                </p>
              </div>
            </div >
                
                   {% for commentaires in commentaire %} 
                  <p ><span>{{commentaires.content}} :{{commentaires.createAt|date('Y-m-d\\H:i:P')}} {% if app.user %}<a style="text-danger" href="{{path('supprimer_commentaire',{'id': commentaires.id})}}"><svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#e01010}</style><path d="M170.5 51.6L151.5 80h145l-19-28.4c-1.5-2.2-4-3.6-6.7-3.6H177.1c-2.7 0-5.2 1.3-6.7 3.6zm147-26.6L354.2 80H368h48 8c13.3 0 24 10.7 24 24s-10.7 24-24 24h-8V432c0 44.2-35.8 80-80 80H112c-44.2 0-80-35.8-80-80V128H24c-13.3 0-24-10.7-24-24S10.7 80 24 80h8H80 93.8l36.7-55.1C140.9 9.4 158.4 0 177.1 0h93.7c18.7 0 36.2 9.4 46.6 24.9zM80 128V432c0 17.7 14.3 32 32 32H336c17.7 0 32-14.3 32-32V128H80zm80 64V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16zm80 0V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16zm80 0V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16z"/></svg></a> {% endif %}</span></p>
                 {% endfor %}
              
      
          </div>
          <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
            <div class="d-flex flex-start w-100">
              <img class="rounded-circle shadow-1-strong me-3"
                src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(19).webp" alt="avatar" width="40"
                height="40" />
              <div class="form-outline w-100">
                   {{form_start(formcommentaire)}}
              <label class="form-label text-light" for="textAreaExample"> {{form_label(formcommentaire.content)}}</label>
                                                                           {{form_widget(formcommentaire.content)}}         
                  
                                                                           {{form_widget(formcommentaire.submit)}}
               
              </div>
            </div>
           
               {{form_end(formcommentaire)}}
           
          </div>

         
        </div>
         
      </div>
       
    </div>
  </div>

  
</section>

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Product{% endblock %}

{% block body %}

 <!--image profile-->
<div  class="container  ">
  <div class="d-flex justify-content-center ">
<img style="width:100px; height:100px" src="{{asset('images/voiture/b7b4b456.png')}}" > 
<img style="width:100px; height:100px" src="{{asset('images/voiture/OIP__2_-removebg-preview.png')}}" > 
<img style="width:100px; height:100px" src="{{asset('images/voiture/R__4_-removebg-preview.png')}}" > 
<img style="width:100px; height:100px" src="{{asset('images/voiture/R__6_-removebg-preview.png')}}" > 
<img style="width:100px; height:100px" src="{{asset('images/voiture/removebg-preview.png')}}" > 
</div>
  <div class ="row">
  <!--reseaux sociaux-->
   <div class="réseaux-sociaux mt-3 d-flex justify-content-center">  
      <a style="font-size:20px" class="text-light ms-5  " href="http://Garage-V.Parrot@gmail.com"> facebook  
  <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#1461e6}</style><path d="M400 32H48A48 48 0 0 0 0 80v352a48 48 0 0 0 48 48h137.25V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.27c-30.81 0-40.42 19.12-40.42 38.73V256h68.78l-11 71.69h-57.78V480H400a48 48 0 0 0 48-48V80a48 48 0 0 0-48-48z"/></svg>
   </a>  
 <!--numero de telephone-->
     <a style="font-size:20px" class="text-light ms-5" href="tel:+33749553121"> Téléphone Service vente voiture: 07.49.55.31.21</a>
     <a style="font-size:20px" class="text-light ms-5" href="mailto:Garage-v.Parrot@gmail.com"> Email: Garage-v.Parrot@gmail.com</a>
    
   </div> 

   <hr class="text-light">


   
         <div class ="col-md-3  text-dark rounded-4 mt-5 container-filter ">
           {% include 'product/_filter.html.twig' with {form: form } only %}
         </div>
         <div class ="col-md-9">
           

           <div  class="grid">
               {% for product in products %}
                  {% include 'product/_cart.html.twig' with {product: product} only  %}
              
               {% endfor %}

             
              </div>
            

              {# display navigation #}
<div class="navigation d-flex justify-content-center mt-3">
    {{ knp_pagination_render(products) }}
</div>
           </div>


              <div class=" commnetaire-note">
             {% include 'product/commentaire.html.twig'%}
              </div>
   </div>
    
    </div>
   
   

   
      
        

{% endblock %}